---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: junos
namespace: junipernetworks
description: Ansible Network Collection for Junipernetworks Junos devices.
readme: README.md
repository: https://github.com/ansible-collections/junipernetworks.junos
issues: https://github.com/ansible-collections/junipernetworks.junos/issues
tags: [juniper, junipernetworks, junos, networking, security, netconf]
version: 5.2.0
