---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.0.1"
license_file: LICENSE
name: junos
namespace: junipernetworks
description: Ansible Network Collection for Junipernetworks Junos devices.
readme: README.md
repository: https://github.com/ansible-collections/junipernetworks.junos
tags: [juniper, junipernetworks, junos, networking, security, netconf]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
