---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: junos
namespace: junipernetworks
readme: README.md
repository: https://github.com/ansible-collections/junipernetworks.junos
tags: [juniper, junipernetworks, junos, networking, security, netconf]
