#
# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the junos_security_zones module
"""


class Security_zonesArgs(object):  # pylint: disable=R0903
    """The arg spec for the junos_security_zones module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'functional_zone_management': {'options': {'description': {'type': 'str'},
                                                                   'host_inbound_traffic': {'options': {'protocols': {'options': {'all': {'options': {'enable': {'type': 'bool'},
                                                                                                                                                      'except': {'type': 'bool'}},
                                                                                                                                          'type': 'dict'},
                                                                                                                                  'names': {'elements': 'str',
                                                                                                                                            'type': 'list'}},
                                                                                                                      'type': 'dict'},
                                                                                                        'system_services': {'options': {'all': {'options': {'enable': {'type': 'bool'},
                                                                                                                                                            'except': {'type': 'bool'}},
                                                                                                                                                'type': 'dict'},
                                                                                                                                        'names': {'elements': 'str',
                                                                                                                                                  'type': 'list'}},
                                                                                                                            'type': 'dict'}},
                                                                                            'type': 'dict'},
                                                                   'interfaces': {'elements': 'str',
                                                                                  'type': 'list'},
                                                                   'screen': {'type': 'str'}},
                                                       'type': 'dict'},
                        'security_zones': {'elements': 'dict',
                                           'options': {'address_book': {'options': {'address_sets': {'elements': 'dict',
                                                                                                     'options': {'address': {'elements': 'str',
                                                                                                                             'type': 'list'},
                                                                                                                 'address_set': {'elements': 'str',
                                                                                                                                 'type': 'list'},
                                                                                                                 'description': {'type': 'str'},
                                                                                                                 'name': {'type': 'str'}},
                                                                                                     'type': 'list'},
                                                                                    'addresses': {'elements': 'dict',
                                                                                                  'options': {'description': {'type': 'str'},
                                                                                                              'dns_name': {'type': 'str'},
                                                                                                              'ip_prefix': {'elements': 'str',
                                                                                                                            'type': 'list'},
                                                                                                              'name': {'type': 'str'},
                                                                                                              'range_address': {'options': {'from': {'type': 'str'},
                                                                                                                                            'to': {'type': 'str'}},
                                                                                                                                'type': 'dict'},
                                                                                                              'wildcard_address': {'type': 'str'}},
                                                                                                  'type': 'list'}},
                                                                        'type': 'dict'},
                                                       'advance_policy_based_routing_profile': {'type': 'str'},
                                                       'application_tracking': {'type': 'bool'},
                                                       'description': {'type': 'str'},
                                                       'enable_reverse_reroute': {'type': 'bool'},
                                                       'host_inbound_traffic': {'options': {'protocols': {'options': {'all': {'options': {'enable': {'type': 'bool'},
                                                                                                                                          'except': {'type': 'bool'}},
                                                                                                                              'type': 'dict'},
                                                                                                                      'names': {'elements': 'str',
                                                                                                                                'type': 'list'}},
                                                                                                          'type': 'dict'},
                                                                                            'system_services': {'options': {'all': {'options': {'enable': {'type': 'bool'},
                                                                                                                                                'except': {'type': 'bool'}},
                                                                                                                                    'type': 'dict'},
                                                                                                                            'names': {'elements': 'str',
                                                                                                                                      'type': 'list'}},
                                                                                                                'type': 'dict'}},
                                                                                'type': 'dict'},
                                                       'interfaces': {'elements': 'str',
                                                                      'type': 'list'},
                                                       'names': {'type': 'str'},
                                                       'screen': {'type': 'str'},
                                                       'source_identity_log': {'type': 'bool'},
                                                       'tcp_rst': {'type': 'bool'}},
                                           'type': 'list'}},
            'type': 'dict'},
 'running_config': {'type': 'str'},
 'state': {'choices': ['merged',
                       'replaced',
                       'overridden',
                       'deleted',
                       'rendered',
                       'gathered',
                       'parsed'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
