#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2022 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for junos_security_policies
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
  'metadata_version': '1.1',
  'status': ['preview'],
  'supported_by': 'network'
}

DOCUMENTATION = """
---
module: junos_security_policies
version_added: 2.9.0
short_description: Create and manage security policies on Juniper JUNOS devices
description: This module provides declarative creation and management of security policies on Juniper JUNOS devices
author: Pranav Bhatt (pbhatt@redhat.com)
requirements:
  - ncclient (>=v0.6.4)
  - xmltodict (>=0.12.0)
notes:
  - This module requires the netconf system service be enabled on the device being managed
  - This module works with connection C(netconf) See L(the Junos OS Platform Options,https://docsansiblecom/ansible/latest/network/user_guide/platform_junoshtml)
  - Tested against JunOS v18.4R1
options:
  config:
    description: A dictionary of security policies
    type: dict
    suboptions:
      from_zones:
        description:
          - List of security zones from which the traffic originates from
        type: list
        elements: dict
        suboptions:
          name:
            description:
              - The name of the security zone from which the traffic originates from
            type: str
          to_zones:
            description:
              - List of destination security zones of the traffic
            type: list
            elements: dict
            suboptions:
              name:
                description:
                  - The name of the destination security zone of the traffic
                type: str
              policies: &policy_attributes
                description:
                  - List of policies defined for the associated category
                type: list
                elements: dict
                suboptions:
                  name:
                    description:
                      - Name of the policy
                    type: str
                  description:
                    description:
                      - Description of the security policy
                    type: str
                  scheduler_name:
                    description:
                      - Name of the scheduler to run this policy
                    type: str
                  match:
                    description: Configure security policy match criteria
                    type: dict
                    suboptions:
                      application:
                        description:
                          - Specify the IP or remote procedure call (RPC) application or set of applications to be used as match criteria
                        type: dict
                        suboptions:
                          names:
                            description: Name of the predefined or custom application or application set used as match criteria
                            type: list
                            elements: str
                          any:
                            description: Match any predefined or custom applications or application sets
                            type: bool
                      dynamic_application:
                        description:
                          - Specify the dynamic applications or dynamic application groups used as match criteria within a security policy
                        type: dict
                        suboptions:
                          names:
                            description: Specify dynamic applications or dynamic application groups
                            type: list
                            elements: str
                          any:
                            description:
                              - Configuring the dynamic application as any installs the policy with the application as a wildcard (default)
                            type: bool
                          none:
                            description:
                              - Configuring the dynamic application as none ignores classification results from AppID and does not use the dynamic application in security policy lookups
                            type: bool
                      destination_address:
                        description:
                          - Define the matching criteria You can specify one or more IP addresses, address sets, or wildcard addresses
                        type: dict
                        suboptions:
                          addresses:
                            description:
                              - IP address, IP address set, or address book entry, or wildcard address (represented as ABCD/wildcard_mask) 
                            type: list
                            elements: str
                          any:
                            description: Any IPv4 or IPv6 address
                            type: bool
                          any_ipv4:
                            description: Any IPv4 address
                            type: bool
                          any_ipv6:
                            description: Any IPv6 address
                            type: bool
                      destination_address_exclude:
                        description:
                          - Exclude destination addresses
                        type: bool
                      source_address:
                        description:
                          - Define the matching criteria You can specify one or more IP addresses, address sets, or wildcard addresses
                        type: dict
                        suboptions:
                          addresses:
                            description:
                              - IP address, IP address set, or address book entry, or wildcard address (represented as ABCD/wildcard_mask) 
                            type: list
                            elements: str
                          any:
                            description: Any IPv4 or IPv6 address
                            type: bool
                          any_ipv4:
                            description: Any IPv4 address
                            type: bool
                          any_ipv6:
                            description: Any IPv6 address
                            type: bool
                      source_address_exclude:
                        description:
                          - Exclude source addresses
                        type: bool
                      source_identity:
                        description:
                          - Identifies users and roles to be used as match criteria for a policy 
                        type: dict
                        suboptions:
                          names:
                            description: A list of specific users and roles
                            type: list
                            elements: str
                          any:
                            description: 
                              - Any user or role, as well as the keywords authenticated_user, unauthenticated_user, 
                                and unknown_user
                            type: bool
                          authenticated_user:
                            description: All users and roles that have been authenticated
                            type: bool
                          unauthenticated_user:
                            description: 
                              - Any user or role that does not have an IP_address mapped to authentication sources and the authentication source is up and running
                            type: bool
                          unknown_user:
                            description: 
                              - Any user or role that does not have an IP address mapped to authentication sources, because the authentication source is disconnected from the SRX Series device 
                            type: bool
                      source_end_user_profile:
                        description: Source end user profile name
                        type: str
                      url_category:
                        description: URL category
                        type: dict
                        suboptions:
                          names:
                            description:
                              - Names of url category to match
                            type: list
                            elements: str
                          any:
                            description:
                              - Apply to any url category
                            type: bool
                          none:
                            description:
                              - Do not apply to the url category
                            type: bool
                      from_zone:
                        description: Identify a single source zone or multiple source zones to be used as a match criteria for a policy 
                        type: dict
                        suboptions:
                          names:
                            description: Name of single or multiple source zone
                            type: list
                            elements: str
                          any:
                            description: Match any zone 
                            type: bool
                          junos_host:
                            description:
                              - junos-host
                            type: bool
                      to_zone:
                        description: Identify a single destination zone or multiple destination zones to be used as a match criteria for a policy 
                        type: dict
                        suboptions:
                          names:
                            description: Name of single or multiple destination zone
                            type: list
                            elements: str
                          any:
                            description: Match any zone 
                            type: bool
                          junos_host:
                            description:
                              - junos-host
                            type: bool
                  then:
                    description: Specify the policy action to be performed when packets match the defined criteria
                    type: dict
                    suboptions:
                      count:
                        description: 
                          - Enable a count, in bytes or kilobytes, of all network traffic the policy allows to pass through the device in both directions; the originating traffic from the client to the server (from the from_zone to the to_zone), and the return traffic from the server to the originating client
                        type: bool
                      deny:
                        description: Block the service at the firewall The device drops the packets
                        type: bool
                      reject:
                        description:
                          - Block the service at the firewall The device drops the packet and sends a TCP reset (RST) segment to the source host for TCP traffic and an ICMP “destination unreachable, port unreachable” message (type 3, code 3) for UDP traffic
                        type: dict
                        suboptions:
                          enable:
                            description:
                              - Enable rejection of packets based on match criteria
                            type: bool
                          profile:
                            description: You can chose to provide a notification to the clients or redirect client request to an informative Web page when a policy blocks HTTP or HTTPS traffic with a deny or reject action
                            type: str
                          ssl_proxy:
                            description: You can apply a redirect SSL proxy profile when a policy blocks HTTPS traffic with a reject action When you apply am SSL proxy profile, SSL proxy decrypts the traffic and application identification functionality identifies the application
                            type: dict
                            suboptions:
                              enable:
                                description:
                                  - Enable SSL proxy
                                type: bool
                              profile_name:
                                description: Name of SSL proxy profile
                                type: str
                      log:
                        description: Log traffic information for a specific policy Traffic information is logged when a session begins (session_init) or closes (session_close)
                        choices:
                          - session-close
                          - session-init
                        type: str
                      permit:
                        description: Block the service at the firewall The device drops the packets
                        type: dict
                        suboptions:
                          application_services:
                            description: 
                              - Enable application services within a security policy
                            type: dict
                            suboptions:
                              advanced_anti_malware_policy:
                                description:
                                  - Specify advanced_anti_malware policy name
                                type: str
                              application_firewalls:
                                description:
                                  - Specify the rule sets configured as part of application firewall to be applied to the permitted traffic 
                                type: list
                                elements: dict
                                suboptions:
                                  rule_set:
                                    description: 
                                      - name of rule set to use
                                    type: str
                              application_traffic_control_rule_set:
                                description:
                                  - Specify the rule set configured as part of AppQoS, application_aware quality of service, to be applied to the permitted traffic 
                                type: str
                              gprs_gtp_profile:
                                description:
                                  - Specify GPRS tunneling protocol profile name
                                type: str
                              gprs_sctp_profile:
                                description:
                                  - Specify GPRS stream control protocol profile name
                                type: str
                              icap_redirect:
                                description:
                                  - Specify icap redirect profile name
                                type: str
                              idp:
                                description:
                                  - Intrusion Detection and Prevention (IDP)
                                type: bool
                              idp_policy:
                                description:
                                  - Specify IDP policy name
                                type: str
                              packet_capture:
                                description:
                                  - Option to enable or disable packet capture
                                type: bool
                              redirect_wx:
                                description:
                                  - Specify the WX redirection needed for the packets that arrive from the LAN 
                                type: str
                              reverse_redirect_wx:
                                description:
                                  - Specify the WX redirection needed for the reverse flow of the packets that arrive from the WAN 
                                type: str
                              security_intelligence_policy:
                                description:
                                  - Specify security_intelligence policy name
                                type: str
                              security_intelligence:
                                description: Specify the security intelligence feed post action
                                type: dict
                                suboptions:
                                  add_destination_identity_to_feed:
                                    description: Add destination user identity to the security feed
                                    type: str
                                  add_destination_ip_to_feed:
                                    description: Add the destination IP address to the security feed
                                    type: str
                                  add_source_ip_to_feed:
                                    description: Add the source IP address to the security feed
                                    type: str
                                  add_source_identity_to_feed:
                                    description: Add source user identity to the security feed
                                    type: str
                              ssl_proxy:
                                description: You can apply a redirect SSL proxy profile when a policy blocks HTTPS traffic with a reject action
                                type: dict
                                suboptions:
                                  enable:
                                    description:
                                      - Enable SSL proxy
                                    type: bool
                                  profile_name:
                                    description: Name of SSL proxy profile
                                    type: str
                              uac_policy:
                                description:
                                  - Enable Unified Access Control (UAC) for the security policy
                                type: dict
                                suboptions:
                                  enable:
                                    description:
                                      - Enable Unified Access Control (UAC)
                                    type: bool
                                  captive_portal:
                                    description:
                                      - Specify the preconfigured security policy for captive portal on the Junos OS Enforcer to enable the captive portal feature
                                    type: str
                              utm_policy:
                                description:
                                  - Specify UTM policy name
                                type: str
                          destination_address:
                            description: 
                              - Specify whether the traffic permitted by the security policy is limited to packets 
                                where the destination IP address has been translated by means of a destination NAT rule 
                                or to packets where the destination IP address has not been translated 
                            choices:
                              - drop-translated
                              - drop-untranslated
                            type: str
                          firewall_authentication:
                            description: Configure firewall authentication methods
                            type: dict
                            suboptions:
                              pass_through:
                                description:
                                  - Configure pass-through firewall user authentication
                                type: dict
                                suboptions:
                                  access_profile:
                                    description:
                                      - Specify the name of the access profile
                                    type: str
                                  client_match:
                                    description:
                                      - Specify the name of the users or user groups in a profile who are allowed access by this policy
                                    type: str
                                  ssl_termination_profile:
                                    description:
                                      - Specify the SSL termination profile used for SSL offloading
                                    type: str
                                  web_redirect:
                                    description:
                                      - Enable redirecting an HTTP request to the device and redirecting the client system to a webpage for authentication
                                    type: bool
                                  web_redirect_to_https:
                                    description:
                                      - Redirect unauthenticated HTTP requests to the internal HTTPS Web server of the device
                                    type: bool
                                  auth_only_browser:
                                    description:
                                      - Configure firewall authentication to ignore non-browser HTTP/HTTPS traffic
                                    type: bool
                                  auth_user_agent:
                                    description:
                                      - Specify a user-agent value to be used to verify that the user's browser traffic is HTTP/HTTPS traffic
                                    type: str
                              push_to_identity_management:
                                description: enables pushing to identity management devices
                                type: bool
                              user_firewall:
                                description:
                                  - Configure user role firewall authentication, and map the source IP address to the username and its associated roles (groups)
                                type: dict
                                suboptions:
                                  access_profile:
                                    description:
                                      - Specify the name of the access profile to be used for authentication
                                    type: str
                                  domain:
                                    description:
                                      - Specify the name of the domain where firewall authentication occurs in the event that the Windows Management Instrumentation client (WMIC)
                                        is not available to get IP_to_user mapping for the integrated user firewall feature
                                    type: str
                                  ssl_termination_profile:
                                    description:
                                      - For HTTPS traffic, specify the name of the SSL termination profile used for SSL offloading
                                    type: str
                                  web_redirect:
                                    description:
                                      - Enable webpage redirection
                                    type: bool
                                  web_redirect_to_https:
                                    description:
                                      - Enable redirection to HTTPS
                                    type: bool
                                  auth_only_browser:
                                    description:
                                      - Configure firewall authentication to ignore non-browser HTTP/HTTPS traffic
                                    type: bool
                                  auth_user_agent:
                                    description:
                                      - Specify a user-agent value to be used to verify that the user's browser traffic is HTTP/HTTPS traffic
                                    type: str
                              web_authentication:
                                description:
                                  - Specify that the policy allows access to users or user groups who have previously been authenticated by Web authentication
                                type: list
                                elements: str
                          tcp_options:
                            description:
                              - Specify the TCP options for each policy You can configure sync and sequence checks for each policy based on your requirements,
                                and, because each policy has two directions, you can configure a TCP MSS value for both directions or for just one direction
                            type: dict
                            suboptions:
                              initial_tcp_mss:
                                description:
                                  - Configure the TCP maximum segment size (MSS) for packets that arrive at the ingress interface (initial direction),
                                    match a specific policy, and for which a session is created 
                                type: int
                              reverse_tcp_mss:
                                description:
                                  - Configure the TCP maximum segment size (MSS) for packets that match a specific policy and travel in the reverse direction of a session
                                type: int
                              sequence_check_required:
                                description:
                                  - Enable sequence check per policy The sequence_check_required value overrides the global value no_sequence_check
                                type: bool
                              syn_check_required:
                                description:
                                  - Enable sync check per policy The syn_check_required value overrides the global value no_syn_check
                                type: bool
                              window_scale:
                                description:
                                  - Enable window_scale per policy
                                type: bool
                          tunnel:
                            description: Encapsulate outgoing IP packets and decapsulate incoming IP packets
                            type: dict
                            suboptions:
                              ipsec_vpn:
                                description:
                                  - name of the ipsec policy
                                type: str
                              pair_policy:
                                description:
                                  - name of the pair policy
                                type: str
      global:
        description:
          - List of global security policies
        type: dict
        suboptions: 
          policies: *policy_attributes
  running_config:
    description:
      - This option is used only with state I(parsed)
      - The value of this option should be the output received from the JunOS device
        by executing the command B(show configuration security policies)
      - The state I(parsed) reads the configuration from C(running_config) option and
        transforms it into Ansible structured data as per the resource module's argspec
        and the value is then returned in the I(parsed) key within the result
    type: str
  state:
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    - rendered
    - gathered
    - parsed
    default: merged
    description:
      - The state the configuration should be left in
      - The states I(rendered), I(gathered) and I(parsed) does not perform any change
        on the device
      - The state I(rendered) will transform the configuration in C(config) option to
        platform specific CLI commands which will be returned in the I(rendered) key
        within the result For state I(rendered) active connection to remote host is
        not required
      - The state I(gathered) will fetch the running configuration from device and transform
        it into structured data in the format as per the resource module argspec and
        the value is returned in the I(gathered) key within the result
      - The state I(parsed) reads the configuration from C(running_config) option and
        transforms it into JSON format as per the resource module parameters and the
        value is returned in the I(parsed) key within the result The value of C(running_config)
        option should be the same format as the output of command
        I(show security policies detail) executed on device For state I(parsed) active
        connection to remote host is not required
    type: str
"""
EXAMPLES = """





















"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.junipernetworks.junos.plugins.module_utils.network.junos.argspec.security_policies.security_policies import Security_policiesArgs
from ansible_collections.junipernetworks.junos.plugins.module_utils.network.junos.config.security_policies.security_policies import Security_policies


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Security_policiesArgs.argument_spec,
                           supports_check_mode=True)

    result = Security_policies(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
